# Message to send if the command is only NPC executable
message: ""

# These commands can only be executed through an NPC
restrictedCommands:
  - command1
  - command2
  - command3

# These permissions will be added and instantly removed when hitting the NPC
permissions:
  - permission1
  - permission2